name: Shell commands

on:
  workflow_dispatch:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v 
          npm -v
      - name: python command
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
      - name: Explain why this job ran
        uses: octo-org/action-name@main
        with:
          entrypoint: /bin/echo
          args: The ${{ github.event_name }} event triggered this step.
